export const visitData = [
    {
      date: '2024-09-01',
      oneTimeVisit: {
        count: 2,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-02',
      oneTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.10',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.11',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.12',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.11',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.12',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.11',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.11',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.12',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.11',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.12',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.11',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-03',
      oneTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smithh',
            phone: '+1-987-654-3210',
            email: 'jane.smith1@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smitth',
            phone: '+1-987-654-3210',
            email: 'jane.smith8@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smiith',
            phone: '+1-987-654-3210',
            email: 'jane.smith7@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smmith',
            phone: '+1-987-654-3210',
            email: 'jane.smith6@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Ssmith',
            phone: '+1-987-654-3210',
            email: 'jane.smith5@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith4@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith3@example.com',
          },
          {
            ipAddress: '192.168.1.10',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith12@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 3,
        customers: [
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }

        ],
      },
    },
    {
      date: '2024-09-04',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.15',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 2,
        customers: [
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
         
        ],
      },
    },
    {
      date: '2024-09-05',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.15',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 1,
        customers: [
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-06',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.15',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 4,
        customers: [
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-07',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.15',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnsonn@example.in',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 1,
        customers: [
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-08',
      oneTimeVisit: {
        count: 4,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 2,
        customers: [
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
        ],
      },
    },
    {
      date: '2024-09-09',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.15',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 1,
        customers: [
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-10',
      oneTimeVisit: {
        count: 2,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-11',
      oneTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smithg@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smitht@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smidth@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smithd@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smithh@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.10',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.11',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.12',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.11',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.12',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.11',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-12',
      oneTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.10',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-13',
      oneTimeVisit: {
        count: 9,
        customers: [
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smitth@example.com',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smithh@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-14',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 1,
        customers: [
          {
            ipAddress: '192.168.1.8',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-15',
      oneTimeVisit: {
        count: 2,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-16',
      oneTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.10',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-17',
      oneTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.10',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-18',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 1,
        customers: [
          {
            ipAddress: '192.168.1.8',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-19',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 1,
        customers: [
          {
            ipAddress: '192.168.1.8',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-20',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 1,
        customers: [
          {
            ipAddress: '192.168.1.8',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-21',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 1,
        customers: [
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-22',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 1,
        customers: [
          {
            ipAddress: '192.168.1.8',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-23',
      oneTimeVisit: {
        count: 4,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 2,
        customers: [
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
        ],
      },
    },
    {
      date: '2024-09-24',
      oneTimeVisit: {
        count: 7,
        customers: [
          {
            ipAddress: '192.168.1.5',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'India',
            details: 'Chris Johnson',
            phone: '+91-12345-67890',
            email: 'chris.johnson@example.in',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
        ],
      },
      multiTimeVisit: {
        count: 1,
        customers: [
          {
            ipAddress: '192.168.1.8',
            country: 'Germany',
            details: 'Sarah Lee',
            phone: '+49-1234-567890',
            email: 'sarah.lee@example.de',
          },
         
        ],
      },
    },
    {
      date: '2024-09-25',
      oneTimeVisit: {
        count: 2,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-26',
      oneTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.10',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-27',
      oneTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.10',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-28',
      oneTimeVisit: {
        count: 9,
        customers: [
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.1',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-29',
      oneTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.10',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
    {
      date: '2024-09-30',
      oneTimeVisit: {
        count: 10,
        customers: [
          {
            ipAddress: '192.168.1.1',
            country: 'USA',
            details: 'John Doe',
            phone: '+1-234-567-8901',
            email: 'john.doe@example.com',
          },
          {
            ipAddress: '192.168.1.2',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.3',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.4',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.5',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.6',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.7',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.8',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.9',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
          {
            ipAddress: '192.168.1.10',
            country: 'Canada',
            details: 'Jane Smith',
            phone: '+1-987-654-3210',
            email: 'jane.smith@example.com',
          },
        ],
      },
      multiTimeVisit: {
        count: 5,
        customers: [
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          },
          {
            ipAddress: '192.168.1.14',
            country: 'France',
            details: 'Bob Martin',
            phone: '+33-9876-543210',
            email: 'bob.martin@example.fr',
          },
          {
            ipAddress: '192.168.1.13',
            country: 'UK',
            details: 'Alice Brown',
            phone: '+44-1234-567890',
            email: 'alice.brown@example.co.uk',
          }
        ],
      },
    },
  ];
  